### ISSUE TITLE
Example/doc/test for transactions?

### ISSUE THREAD

**Issue by achimnol** [gaopeiliang/aioetcd3#1]
I'm converting existing ectd3 codes to aioetcd3.

```python3
from aioetcd3.kv import _put_request
from aioetcd3.transaction import Value

async def do():
    ...
    success, meta = await self.etcd.txn(
        [Value(key) == initial_val],
        [(_put_request(key, new_val), None)],  # success
        [],  # fail
    )
```

This code generates errors when the "success" case is executed.
I think the API is not complete yet, as there is nothing corresponding to `etcd3.transactions.Put`.

Is there any way to write transactions in the current version or should I wait for the next release?

**Comment by achimnol** [comment]
The problem is that `return True, [t[1](r) for t, r in zip(success, response.responses)]` in `_create_txn_response_builder` function breaks when the comparison was successful.
As a workaround, if I change the return statements to `return True, None` / `return False, None`, then it works as expected without `meta`.

**Comment by hubo1016** [comment]
It's rather simple

```python
async def do():
    ...
    success, meta = await self.etcd.txn(
        [Value(key) == initial_val],
        [self.etcd.put.txn(key, new_val)],  # success
        [],  # fail
    )
```

**Comment by hubo1016** [comment]
All methods in KV mixin have a `txn` attribute, which is a function. It accepts the exactly same arguments as the root method, and returns the necessary arguments for `KV.txn()`. Notice that `KV.txn()` also has `KV.txn.txn()` function.

**Comment by achimnol** [comment]
Thanks for quick reply!
