### ISSUE TITLE
Multiple simultaneous watchers are broken

### ISSUE THREAD

**Issue by achimnol** [gaopeiliang/aioetcd3#2]
I force-enabled the watch API by uncommenting import of `Watch` class in client.py and add it to the base class list of `Client`.
It seems to work well with a single watcher (despite a lot of errors when closing the event loop), but if I set up two or more overlapped watchers that listens to events simulataneously then all watchers seem to receive the same set of events that the first watcher receives.
Maybe, is this the reason *not* to include the watch API yet?

**Comment by gaopeiliang** [comment]
Next release we will add the restruct watch API !

**Comment by achimnol** [comment]
Yep, so it is still under development. Thanks!
