### ISSUE TITLE
Is it safe to use in multiprocessing (separate event loops for each worker process)?

### ISSUE THREAD

**Issue by achimnol** [gaopeiliang/aioetcd3#4]
I began to see hang-up/blocking issues after I have replaced my etcd wrapper with a new version that uses aioetcd3 in a multi-process Python application. All worker processes get stuck at the point of first calling `await etcd.put(...)`.
I'd just quickly check if it's safe to use aioetcd3 in multi-process setup where event loops are spawned for each worker process.

**Comment by hubo1016** [comment]
Is there any example code?

Usually it is NOT safe for a multi-threading (yes, grpc.io C core is using multiple threads) process to do fork. So I think it is only safe to create separated etcd clients in each worker process.

**Comment by hubo1016** [comment]
Also it is not safe to fork an asyncio program with a running event loop. The event loop creates a pipe to wake up the event loop from other threads. If the program is forked, the pipe is shared and the notification may be received by a wrong process.

**Comment by achimnol** [comment]
Yes, I already know how to do properly multi-process asyncio programs. I have instantiated etcd clients individually after initializing separate event loops within each worker process, without sharing any loop-related objects.

What I'm curious about is multiprocess-safety of aioetcd3 / aiogrpc.

* Is it safe to use separate instances of aioetcd3 client in all separate event loops spawend after forking multiple processed and inside them (one process = one event loop = one client)?
* Is it safe to use a single instance of aioetcd3 client in an only one event loop among separate event loops spawned after forking multiple processes and inside them?

**Comment by achimnol** [comment]
The code is [here](https://github.com/lablup/backend.ai-manager/tree/develop) and the exact line stuck is [here](https://github.com/lablup/backend.ai-manager/blob/develop/ai/backend/gateway/etcd.py#L15), but it would be too mcuh complicated to install and test for now. This project uses [aiotools.server](https://github.com/achimnol/aiotools/blob/master/aiotools/server.py) to spawn multiple children processes with individual event loops.
I'm using a hybrid wrapper of etcd3 and aioetcd3 [here](https://github.com/lablup/backend.ai-common/blob/master/ai/backend/common/etcd.py) with [some basic test cases](https://github.com/lablup/backend.ai-common/blob/master/tests/test_etcd.py).
But as aioetcd3 v1.5 is just released with a new watch API, so this will be updated soon.

**Comment by hubo1016** [comment]
I'll look at it later, but I'm on a vacation next week. It will be very helpful if you can provide a simple runnable script that reproduces this bug.

**Comment by achimnol** [comment]
I have written a minimal example code to demonstrate the problem.
https://gist.github.com/achimnol/b58810467db011a2f13323b3fab1ed9a

If you change `use_threading=False` (multiprocessing-based) to `use_threading=True` (threading-based), then it works.

**Comment by achimnol** [comment]
I just discovered that it *works* if I move the `from aioetcd3.client import client` statements into the worker function.
This means that importing aiotecd3 before forks has side-effects when forking afterwards.

**Comment by achimnol** [comment]
https://groups.google.com/forum/#!topic/grpc-io/-jQ6lmJt-jc
https://github.com/grpc/grpc/issues/7951#issuecomment-244136180
https://github.com/grpc/grpc/issues/7951#issuecomment-260811550

So this hang-up issue with aioetcd3 is caused by the internal design of gRPC library itself (which aiogrpc depends on).
It seems that there is no way to "fix" this but only we can workaround by importing/initializing aioetcd3 *after* forking. I also found that this issue exists in etcd3 as well.

I'm closing this issue as it's turned out to be out of scope of aioetcd3.
