### ISSUE TITLE
watch method should re-raise asyncio.CancelledError

### ISSUE THREAD

**Issue by achimnol** [gaopeiliang/aioetcd3#8]
The watch method catches all exception when `always_reconnect=True`.
This is not desirable because there is no way to gracefully shutdown the watcher.
Or, maybe it is better to provide another method to cancel the watchers explicitly since etcd itself provides a way to cancel (deregister) watchers.

**Comment by hubo1016** [comment]
Capture asyncio.CancelledError is a bug, it should be fixed.

**Comment by gaopeiliang** [comment]
#9
